- recipes/monitoring.rb
- spec/unit/recipes/monitoring_spec.rb
We need to run the resource on each node with a differet key name so let's do it
by hostname.
> Create per node nagios auth keys

- kitchen.yml
Whoops! Looks like this PR was still in the drafts.
> Update multi-node configuration

- resources/ceph_keyring.rb
- resources/osl_cephfs.rb
Added `unified_mode true`
- ceph_keyring
- osl_cephfs
> Enable unified_mode on custom resource

- .rubocop.yml
- metadata.rb
Corresponding pin bump for osuosl-cookbooks/ceph-chef#5.
> Bump ceph-chef version

- resources/osl_cephfs.rb
This allows us to skip :mount in test-kitchen more easily.
> Add :enable action to osl_cephfs

- metadata.rb
- recipes/default.rb
- recipes/mds.rb
- recipes/mgr.rb
- recipes/mon.rb
- recipes/monitoring.rb
- recipes/nagios.rb
- recipes/osd.rb
- Cookstyle fixes
- Use osl-repos::epel
> EPEL fixes

- resources/keyring.rb
- spec/unit/resources/ceph_keyring_spec.rb
- test/cookbooks/ceph_test/recipes/ceph_keyring.rb
- test/integration/config/controls/config.rb
> Fix typo in parameter name in keyring resource

- recipes/nagios.rb
- spec/unit/recipes/nagios_spec.rb
We need to make sure we handle each release differently as there are changes
between them.
> nagios: Set a branch to use for the ceph-nagios-plugins repository

- libraries/helpers.rb
- resources/install.rb
- spec/unit/resources/install_spec.rb
- test/integration/default/controls/default_spec.rb
- test/integration/mgr/controls/mgr.rb
- Add ceph-noarch repository which has the dashboard package
- Also install the disk prediction packages
> Add mgr dashboard package

- kitchen.multi-node.yml
- metadata.rb
- spec/unit/recipes/default_spec.rb
- spec/unit/recipes/mds_spec.rb
- spec/unit/recipes/mgr_spec.rb
- spec/unit/recipes/mon_spec.rb
- spec/unit/recipes/monitoring_spec.rb
- spec/unit/recipes/nagios_spec.rb
- spec/unit/recipes/osd_spec.rb
- spec/unit/resources/ceph_keyring_spec.rb
- spec/unit/resources/cephfs_spec.rb
- spec/unit/resources/client_spec.rb
- spec/unit/resources/config_spec.rb
- spec/unit/resources/install_spec.rb
- spec/unit/resources/mds_spec.rb
- spec/unit/resources/mgr_spec.rb
- spec/unit/resources/mon_spec.rb
- spec/unit/resources/rbdmap_spec.rb
- spec/unit/resources/test_spec.rb
- test/integration/mds/controls/mds.rb
- test/integration/multi-node/controls/cephfs_spec.rb
> Remove support for CentOS 7

- test/cookbooks/ceph_test/recipes/multinode_network.rb
> Update to new refactors osl_ifconfig resource

- resources/config.rb
- spec/unit/resources/config_spec.rb
- spec/unit/resources/radosgw_spec.rb
- templates/ceph.conf.erb
> Allow setting of rgw_dns_name to a static name

- recipes/default.rb
> Add rgw_dns_name to default recipe

- main.tf
- recipes/nagios.rb
- resources/install.rb
- spec/unit/recipes/nagios_spec.rb
- spec/unit/resources/install_spec.rb
- test/cookbooks/ceph_test/recipes/mgr.rb
- test/integration/default/controls/default_spec.rb
- test/integration/multi-node/controls/ceph_nodes_spec.rb
- variables.tf
> Update to Octopus release

- recipes/default.rb
- resources/install.rb
This doesn't work inside of a custom resource
> Move edit_resource to default recipe

- libraries/helpers.rb
- provider.tf
- recipes/nagios.rb
- resources/install.rb
- resources/test.rb
- spec/unit/recipes/nagios_spec.rb
- spec/unit/resources/install_spec.rb
- test/cookbooks/ceph_test/recipes/mgr.rb
- test/cookbooks/ceph_test/recipes/mon.rb
- test/cookbooks/ceph_test/recipes/mon_keys.rb
- test/cookbooks/ceph_test/recipes/multinode_cephfs.rb
- test/cookbooks/ceph_test/recipes/multinode_node1.rb
- test/integration/default/controls/default_spec.rb
- test/integration/mgr/controls/mgr.rb
- test/integration/multi-node/controls/ceph_nodes_spec.rb
- test/integration/radosgw/controls/radosgw.rb
> Update to Pacific release

- recipes/default.rb
- resources/config.rb
- spec/unit/resources/config_spec.rb
- templates/ceph.conf.erb
> Add support for s3website and cname buckets

- kitchen.multi-node.yml
- kitchen.openstack.yml
- kitchen.yml
- main.tf
- metadata.rb
- recipes/nagios.rb
- resources/install.rb
- resources/mon.rb
- spec/unit/recipes/nagios_spec.rb
- spec/unit/resources/install_spec.rb
- spec/unit/resources/mon_spec.rb
- test/integration/default/controls/default_spec.rb
- test/integration/mds/controls/mds.rb
- test/integration/multi-node/controls/ceph_nodes_spec.rb
- test/integration/multi-node/controls/cephfs_spec.rb
> Update to Quincy release

- libraries/helpers.rb
- resources/install.rb
- spec/unit/resources/install_spec.rb
Having issues running quincy on POWER8.
> Revert back to pacific on ppc64le

- libraries/helpers.rb
- resources/install.rb
- spec/unit/resources/install_spec.rb
Reverts osuosl-cookbooks/osl-ceph#61
> Revert "Revert back to pacific on ppc64le"

- resources/test.rb
- spec/unit/resources/test_spec.rb
> Install ceph-volume in the ceph_test resource

- libraries/helpers.rb
- spec/unit/resources/install_spec.rb
- test/integration/mgr/controls/mgr.rb
This is causing issues and we aren't really using it.
> Remove ceph-mgr-diskprediction-local

- libraries/helpers.rb
- recipes/default.rb
- recipes/mds.rb
- recipes/mgr.rb
- recipes/mon.rb
- recipes/monitoring.rb
- recipes/nagios.rb
- recipes/osd.rb
- recipes/radosgw.rb
- resources/install.rb
> Install 17.2.8 on aarch64 on EL9
