osuosl-cookbooks/osl-ceph

recipes/monitoring.rb, spec/unit/recipes/monitoring_spec.rb
In clusters where we have the MON nodes split up from the OSD nodes, this breaks
NRPE checks. This just uses what's in the ceph.conf to figure out where to
query.
=> Don't assume the OSD node also is a mon node

.kitchen.yml, test/cookbooks/ceph_test/recipes/default.rb, test/cookbooks/ceph_test/templates/default/volume.rb.erb, test/integration/roles/ceph.json
With the switch to actually using Ceph in the backend, we've updated the how the
system see the disks as well. So now instead of seeing vda we see sda for
example. This makes no changes for production and only in test-kitchen and chef
provisioning test environments
=> Update test environment to use sdX instead of vdX

.kitchen.yml, recipes/monitoring.rb, recipes/nagios.rb, spec/unit/recipes/nagios_spec.rb, test/integration/nagios/nagios_spec.rb
This allows us to use this recipe in other places where we don't need to setup
ceph keys such as in osl-nagios.
=> Split nagios plugin installation into its own recipe

recipes/default.rb
The execute[change-ceph-conf-perm] resource does a blanket chown -R ceph:ceph
/etc/ceph which interferes with setting files inside of the directory.
=> Remove execute[change-ceph-conf-perm] resource

.kitchen.yml, recipes/mds.rb, spec/spec_helper.rb, spec/unit/recipes/mds_spec.rb, test/cookbooks/ceph_test/files/default/crush_map_decompressed, test/cookbooks/ceph_test/recipes/mds.rb, test/cookbooks/ceph_test/recipes/osd.rb, test/integration/mds/mds_spec.rb, test/integration/mds/mgr_spec.rb, test/integration/mds/mon_spec.rb, test/integration/mds/osd_spec.rb, test/integration/roles/ceph_mds.json
This adds the MDS daemon as a recipe which is required to utilize cephfs. This
required the following changes to make it happen:
- Some fixes in ceph-chef
- Update the crush map for test-kitchen to allow for single-node ceph clusters
- Create pg's for cephfs, create cephfs and mount it
- Set the mon key to something static to get it to work with test-kitchen
Edit:
**Note: running the ``test`` action on the mds suite will most likely return an error. If you want around 30 seconds and try again with ``verify`` it should pass. This is due to the fact that ceph needs a few seconds to spin things up properly**
=> Add MDS (metadata server) recipe

metadata.rb, recipes/mgr.rb, spec/unit/recipes/mgr_spec.rb
This upgrades this cookbook to use the latest version of the systemd cookbook
and switches to using the ``systemd_service_drop_in`` resource.
=> Update to using systemd_service_drop_in

.rubocop.yml, Berksfile, recipes/default.rb, recipes/mds.rb, recipes/mgr.rb, recipes/mon.rb, recipes/monitoring.rb, recipes/nagios.rb, recipes/osd.rb, resources/osl_cephfs.rb, spec/unit/resources/osl_cephfs_spec.rb
This works around this issue [1] so that mount works properly if we end up using the root mount point with cephfs.
Other changes:
- Cookstyle fixes
- Add osl-repos to Berksfile
- Update ChefSpec to test cephfs with a ceph mon server showing up properly
[1] https://github.com/chef/chef/issues/10764
=> Implement workaround for mount bug in Chef

resources/osl_cephfs.rb
This will pass mount options which is useful in test-kitchen environments by adding noauto.
=> Add options property to osl_cephfs resource

recipes/mgr.rb, spec/unit/recipes/mgr_spec.rb
On EL7 this is the correct place, however on newer versions of systemd this will need to back to Unit.
=> Move StartLimitBurst to Service

main.tf, provider.tf, test/cookbooks/ceph_test/recipes/multinode_osd.rb
This allows us to test doing reboots and such on a VM and more closely mimics
how this looks on a real system. Using a loopback device is fine with single
nodes, but not for multi nodes.
=> multi-node: Switch to using cinder volumes

README.md, kitchen.multi-node.yml, main.tf, metadata.rb, recipes/nagios.rb, resources/install.rb, resources/mon.rb, resources/test.rb, spec/unit/recipes/nagios_spec.rb, spec/unit/resources/config_spec.rb, spec/unit/resources/install_spec.rb, spec/unit/resources/mon_spec.rb, templates/ceph.conf.erb, test/cookbooks/ceph_test/recipes/multinode_cephfs.rb, test/cookbooks/ceph_test/recipes/multinode_network.rb, test/cookbooks/ceph_test/recipes/multinode_node1.rb, test/integration/default/controls/default_spec.rb, test/integration/mds/controls/mds.rb, test/integration/mon/controls/mon.rb, test/integration/multi-node/controls/ceph_nodes_spec.rb, test/integration/multi-node/controls/cephfs_spec.rb, test/integration/osd/controls/osd.rb
- Add support for AlmaLinux 8
- Remove `--set-uid` as it's now deprecated
- Disable `global_id` warnings for testing purposes (test-kitchen only)
- Enable `msgr2` so warnings go away (test-kitchen only)
- Fix path to mon keyring
- Update tests to match output with Nautilus
=> Update to Nautilus release

resources/test.rb, spec/unit/resources/test_spec.rb
Add `ipaddress` parameter which is useful with multi-node openstack testing. Defaults to `node['ipaddress']`.
=> osl_ceph_test: add ipaddress parameter

libraries/helpers.rb
This fixes idempotency issues in some situations (i.e. osl-openstack).
=> Also check for fsid in attributes

.rubocop.yml, kitchen.yml, metadata.rb, recipes/default.rb, recipes/mds.rb, recipes/mgr.rb, recipes/mon.rb, recipes/monitoring.rb, recipes/nagios.rb, recipes/osd.rb, resources/rbdmap.rb, spec/unit/resources/rbdmap_spec.rb, test/cookbooks/ceph_test/recipes/rbdmap.rb, test/integration/rbdmap/controls/rbdmap_spec.rb, test/integration/rbdmap/inspec.yml
This is useful when mapping rbd images to devices such as on ftp-osl.
=> Add osl_ceph_rbdmap resource

recipes/osd.rb, spec/unit/recipes/osd_spec.rb
This allows us to recreate OSD's on nodes which was missing in the refactor.
Skip creating it if the bootstrap isn't included in the databag as this can't be
created on an initial run.
=> Add bootstrap-osd keyring

kitchen.yml, recipes/osd.rb, spec/unit/recipes/osd_spec.rb, test/cookbooks/ceph_test/recipes/osd.rb, test/integration/osd/controls/osd.rb
Ensure NVMe LV's get scanned for partitions before ceph-osd starts. These DO NOT
get scanned on boot because they are logical volumes and OSDs will fail to start
if they use them.
Also add missing inclusion of OSD tests in the osd suite :facepalm:
=> Start partprobe on boot before Ceph

recipes/default.rb
Let's make sure we includes the osl-repos::alma recipein the default recipe so
the synergy repo doesn't keep flapping on chef runs.
=> Fix idempotency issues in production

resources/test.rb, spec/unit/resources/test_spec.rb
This was missed since previous images already contained lvm2.
=> Install lvm2 when using the ceph_test resource

resources/install.rb, spec/unit/resources/install_spec.rb
They removed EL8 builds with 17.2.8.
=> Temporary workaround for issue with upstream repo

recipes/nagios.rb
This will fix an idempotency issue we're seeing on the nagios server.
=> Switch to including osl-ceph instead of using osl_ceph_install

resources/install.rb
This fixes an idempotency issue we were having on nodes that included
osl-apache.
=> Switch to using find_resource

Berksfile, recipes/osd.rb, spec/unit/recipes/osd_spec.rb
Some OSD nodes use different names if we have more than one NVMe installed. This
ensures we scan those on boot too.
Also switch to using private supermarket.
=> Also check for nvme-1 and nvme-2 paths for partprobe
